import type { ModuleId } from "@/lib/permissions";

export type HelpTopicType = "documentation" | "guide" | "tutorial";

export type HelpErrorDetail = {
  errorNumber: number;
  code: string;
  httpStatus: number;
  title: string;
  meaning: string;
  commonCause: string;
  fixSteps: string[];
};

export type HelpArticleSection = {
  heading: string;
  paragraphs: string[];
  checklist?: string[];
  warnings?: string[];
};

export type HelpTopic = {
  id: string;
  title: string;
  summary: string;
  type: HelpTopicType;
  module: ModuleId;
  relatedHref: string;
  tags: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
  audience: string[];
  articleSections: HelpArticleSection[];
  whenToUse: string[];
  steps: string[];
  tips: string[];
  errorDetails: HelpErrorDetail[];
  updatedAt: string;
};

export const MODULE_LABEL: Record<ModuleId, string> = {
  home: "Home",
  tasks: "Tasks",
  projects: "Projects",
  documents: "Documents",
  email: "E-Mail",
  board: "Board",
  leads: "Leads",
  clients: "Organizations",
  contacts: "Contacts",
  team: "Team",
  calendar: "Calendar",
  chat: "Chat",
  livechat: "Live Chat",
  servicedesk: "Ticket Desk",
  products: "Products",
  accounting: "Accounting",
  ebank: "e-Bank",
  telephony: "Telephony",
  search: "Search",
  help: "Help",
  administration: "Administration",
};

export const TOPIC_TYPE_LABEL: Record<HelpTopicType, string> = {
  documentation: "Documentation",
  guide: "Guide",
  tutorial: "Tutorial",
};

const UPDATED_AT = "2026-03-31";

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: "help-getting-started",
    title: "Getting Started With DevotionDash",
    summary: "Role-aware onboarding with practical first-day checks.",
    type: "documentation",
    module: "help",
    relatedHref: "/home",
    tags: ["onboarding", "permissions", "navigation"],
    difficulty: "beginner",
    audience: ["All users", "Admins"],
    articleSections: [
      {
        heading: "Access Model",
        paragraphs: [
          "Visibility is controlled by module permissions.",
          "Read shows module, write allows changes, and manage enables control actions.",
        ],
        checklist: ["Confirm role template", "Confirm user override mode", "Confirm module toggles"],
      },
      {
        heading: "First-Day Validation",
        paragraphs: [
          "Run one end-to-end flow: task, document, chat, and stage update.",
          "If an action is missing, compare behavior with an admin account first.",
        ],
      },
    ],
    whenToUse: ["New onboarding", "Permission troubleshooting", "Post-deploy validation"],
    steps: ["Open Home", "Run Search query", "Create sample task", "Upload sample document", "Send chat message", "Verify counters"],
    tips: ["Search before create", "Keep stage updates current", "Use Help by module"],
    errorDetails: [
      {
        errorNumber: 1001,
        code: "AUTH_UNAUTHORIZED",
        httpStatus: 401,
        title: "Unauthorized",
        meaning: "Session is not valid.",
        commonCause: "Expired token or stale cookies.",
        fixSteps: ["Re-login", "Clear site cookies", "Verify auth secret and system time"],
      },
      {
        errorNumber: 1002,
        code: "AUTH_FORBIDDEN",
        httpStatus: 403,
        title: "Forbidden",
        meaning: "Permission denied for requested action.",
        commonCause: "Role or override does not grant module action.",
        fixSteps: ["Check role permissions", "Check user overrides", "Retest with admin"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "home-daily-operations",
    title: "Home Module: Daily Operations View",
    summary: "Use Home cards as a reliable command center.",
    type: "guide",
    module: "home",
    relatedHref: "/home",
    tags: ["home", "cards", "navigation"],
    difficulty: "beginner",
    audience: ["All users"],
    articleSections: [
      {
        heading: "Expected Behavior",
        paragraphs: ["Cards should be visible by permission and clickable.", "Counters should match module list counts."],
      },
      {
        heading: "Daily Rhythm",
        paragraphs: ["Open Home first, then jump to Tasks, Chat, and Calendar.", "Use Home for visibility; perform updates inside modules."],
      },
    ],
    whenToUse: ["Daily start", "Card troubleshooting", "Route wiring checks"],
    steps: ["Open Home", "Click each card", "Compare counters", "Refresh and recheck responsiveness"],
    tips: ["Keep Home lightweight", "Investigate counter mismatch immediately"],
    errorDetails: [
      {
        errorNumber: 1201,
        code: "HOME_WIDGET_LOAD_FAILED",
        httpStatus: 500,
        title: "Home Widget Load Failed",
        meaning: "Dashboard widget data did not load.",
        commonCause: "Backend query or parsing failure.",
        fixSteps: ["Refresh page", "Check endpoint logs", "Validate payload fields"],
      },
      {
        errorNumber: 1202,
        code: "HOME_CARD_ROUTE_INVALID",
        httpStatus: 404,
        title: "Card Route Invalid",
        meaning: "Card links to unavailable route.",
        commonCause: "Outdated route mapping.",
        fixSteps: ["Update module href mapping", "Retest card click path"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "tasks-lifecycle",
    title: "Tasks Module: Lifecycle, Stages, and Counter Accuracy",
    summary: "Detailed stage management with panel and scope consistency.",
    type: "guide",
    module: "tasks",
    relatedHref: "/tasks",
    tags: ["tasks", "stages", "scope", "counters"],
    difficulty: "intermediate",
    audience: ["Managers", "Agents"],
    articleSections: [
      {
        heading: "Stage Rules",
        paragraphs: ["Move tasks by real progress.", "Terminal stage label and panel counting logic must match."],
      },
      {
        heading: "Scope Behavior",
        paragraphs: ["Subordinate, assigned, and all scopes should use consistent filters.", "Scope switch should not zero counters unexpectedly."],
      },
    ],
    whenToUse: ["Task panel mismatch", "Workflow tuning", "Execution tracking"],
    steps: ["Create task", "Move stages during work", "Add closure note", "Verify panel counts", "Retest scope filters"],
    tips: ["Use one terminal stage key", "Audit stage mapping after rename"],
    errorDetails: [
      {
        errorNumber: 2001,
        code: "TASK_VALIDATION_FAILED",
        httpStatus: 400,
        title: "Task Validation Failed",
        meaning: "Input is incomplete or invalid.",
        commonCause: "Missing title or invalid stage.",
        fixSteps: ["Fill required fields", "Use valid stage key"],
      },
      {
        errorNumber: 2002,
        code: "TASK_COUNTER_MISMATCH",
        httpStatus: 409,
        title: "Task Counter Mismatch",
        meaning: "Panel counts differ from list data.",
        commonCause: "Filter or terminal stage mapping inconsistency.",
        fixSteps: ["Verify scope filters", "Verify terminal stage mapping", "Refresh state"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "projects-delivery",
    title: "Projects Module: Planning, Phases, and Delivery",
    summary: "Run projects with phase discipline and task parity.",
    type: "tutorial",
    module: "projects",
    relatedHref: "/projects",
    tags: ["projects", "phases", "kanban", "delivery"],
    difficulty: "intermediate",
    audience: ["Project managers", "Leads"],
    articleSections: [
      {
        heading: "Project Structure",
        paragraphs: ["Set objective, owner, timeline, and milestones.", "Keep project tasks aligned with Tasks module behavior."],
      },
      {
        heading: "Execution Control",
        paragraphs: ["Review blocked items daily.", "Close project only after acceptance checklist."],
      },
    ],
    whenToUse: ["Multi-step work", "Cross-team delivery", "Milestone reporting"],
    steps: ["Create project", "Define phases", "Add tasks", "Track progress", "Resolve blockers", "Close with sign-off"],
    tips: ["Split unrelated work", "Use phase naming standards"],
    errorDetails: [
      {
        errorNumber: 3001,
        code: "PROJECT_LOAD_FAILED",
        httpStatus: 500,
        title: "Project Load Failed",
        meaning: "Project data failed to load.",
        commonCause: "Server query or relation issue.",
        fixSteps: ["Retry", "Check endpoint logs", "Validate relation mapping"],
      },
      {
        errorNumber: 3002,
        code: "PROJECT_TASK_STAGE_INVALID",
        httpStatus: 400,
        title: "Invalid Project Task Stage",
        meaning: "Requested stage is not configured.",
        commonCause: "Stage key mismatch after workflow update.",
        fixSteps: ["Use active stage key", "Update client mapping"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "documents-governance",
    title: "Documents Module: Upload, Open, and Share Governance",
    summary: "File lifecycle guide with permission and preview reliability.",
    type: "documentation",
    module: "documents",
    relatedHref: "/documents",
    tags: ["documents", "upload", "preview", "sharing"],
    difficulty: "intermediate",
    audience: ["All users"],
    articleSections: [
      {
        heading: "Upload and Open Flow",
        paragraphs: ["Verify metadata immediately after upload.", "Show progress on large open/download operations."],
      },
      {
        heading: "Permission Model",
        paragraphs: ["Folder sharing is broad; file sharing is precise.", "Review shares for private files regularly."],
        warnings: ["Do not expose file URLs without permission checks"],
      },
    ],
    whenToUse: ["Document access setup", "Preview issues", "Share audits"],
    steps: ["Upload file", "Verify metadata", "Open file", "Share with users", "Validate recipient access"],
    tips: ["Use clear filenames", "Keep folder taxonomy consistent"],
    errorDetails: [
      {
        errorNumber: 4001,
        code: "DOCUMENT_UPLOAD_FAILED",
        httpStatus: 500,
        title: "Document Upload Failed",
        meaning: "File was not stored successfully.",
        commonCause: "Storage permission or transport interruption.",
        fixSteps: ["Retry upload", "Check storage permissions", "Check upload route logs"],
      },
      {
        errorNumber: 4002,
        code: "DOCUMENT_ACCESS_DENIED",
        httpStatus: 403,
        title: "Document Access Denied",
        meaning: "User lacks read access for this file.",
        commonCause: "Missing share or restrictive folder policy.",
        fixSteps: ["Grant read share", "Verify inheritance rules"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "email-operations",
    title: "E-Mail Module: Mailbox and Queue Operations",
    summary: "Detailed mailbox setup, thread hygiene, and queue recovery.",
    type: "guide",
    module: "email",
    relatedHref: "/email",
    tags: ["email", "mailbox", "queue", "threads"],
    difficulty: "intermediate",
    audience: ["Support", "Sales", "Admins"],
    articleSections: [
      {
        heading: "Mailbox Reliability",
        paragraphs: ["Test inbound and outbound after credential changes.", "Keep mailbox ownership clear for team operations."],
      },
      {
        heading: "Queue Recovery",
        paragraphs: ["Failed queue items must show reason and retry controls.", "Resolve hard failures before retrying."],
      },
    ],
    whenToUse: ["Mailbox onboarding", "Delivery failures", "Thread cleanup"],
    steps: ["Configure mailbox", "Run send/receive test", "Use templates", "Review queue failures", "Retry after root-cause fix"],
    tips: ["Keep subjects consistent", "Avoid duplicate parallel replies"],
    errorDetails: [
      {
        errorNumber: 13001,
        code: "EMAIL_MAILBOX_AUTH_FAILED",
        httpStatus: 401,
        title: "Mailbox Authentication Failed",
        meaning: "Mailbox credentials were rejected.",
        commonCause: "Password or token changed/expired.",
        fixSteps: ["Update credentials", "Retest mailbox connection"],
      },
      {
        errorNumber: 13002,
        code: "EMAIL_QUEUE_DELIVERY_FAILED",
        httpStatus: 502,
        title: "Queue Delivery Failed",
        meaning: "Queued message failed transport.",
        commonCause: "SMTP/API transport error or invalid payload.",
        fixSteps: ["Inspect failure reason", "Fix settings/payload", "Retry item"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "board-collaboration",
    title: "Board Module: Visual Work Coordination",
    summary: "Detailed board operation for lane clarity and WIP control.",
    type: "tutorial",
    module: "board",
    relatedHref: "/board",
    tags: ["board", "kanban", "wip", "collaboration"],
    difficulty: "intermediate",
    audience: ["Teams", "Coordinators"],
    articleSections: [
      {
        heading: "Lane Design",
        paragraphs: ["Use clear stage names with exit criteria.", "Limit lane count to keep decisions fast."],
      },
      {
        heading: "Card Movement Rules",
        paragraphs: ["Move cards in real time as work changes.", "Blocked cards need owner and blocker reason."],
      },
    ],
    whenToUse: ["Standups", "Flow bottleneck analysis", "Team planning"],
    steps: ["Define lanes", "Set WIP limits", "Assign owners", "Move cards by progress", "Review blocked lane daily"],
    tips: ["Avoid stage sprawl", "Keep card titles actionable"],
    errorDetails: [
      {
        errorNumber: 14001,
        code: "BOARD_CARD_MOVE_FAILED",
        httpStatus: 409,
        title: "Card Move Failed",
        meaning: "Board move did not persist.",
        commonCause: "Conflict or invalid target lane.",
        fixSteps: ["Refresh board", "Retry move", "Verify lane key validity"],
      },
      {
        errorNumber: 14002,
        code: "BOARD_LAYOUT_INVALID",
        httpStatus: 400,
        title: "Invalid Board Layout",
        meaning: "Lane definition is malformed.",
        commonCause: "Duplicate or missing lane keys.",
        fixSteps: ["Normalize lane keys", "Save board config again"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "leads-pipeline",
    title: "Leads Module: Pipeline Execution and Conversion",
    summary: "Detailed lead flow from intake to win/loss tracking.",
    type: "documentation",
    module: "leads",
    relatedHref: "/leads",
    tags: ["leads", "pipeline", "conversion"],
    difficulty: "intermediate",
    audience: ["Sales", "CRM managers"],
    articleSections: [
      {
        heading: "Data Quality Rules",
        paragraphs: ["Capture source, owner, and next action for each lead.", "No lead should remain without follow-up plan."],
      },
      {
        heading: "Stage Control",
        paragraphs: ["Advance stage only after criteria is met.", "Record reason on lost opportunities for analytics."],
      },
    ],
    whenToUse: ["Sales pipeline management", "Conversion reporting", "Lead hygiene"],
    steps: ["Create lead", "Assign owner", "Log interactions", "Advance stage", "Convert or close with reason"],
    tips: ["Set first-response SLA", "Review stalled leads weekly"],
    errorDetails: [
      {
        errorNumber: 8001,
        code: "LEAD_STAGE_TRANSITION_BLOCKED",
        httpStatus: 400,
        title: "Lead Stage Transition Blocked",
        meaning: "Stage move violates flow rules.",
        commonCause: "Invalid transition or missing permission.",
        fixSteps: ["Check transition rules", "Grant required permission", "Retry with valid stage"],
      },
      {
        errorNumber: 8002,
        code: "LEAD_OWNER_REQUIRED",
        httpStatus: 400,
        title: "Lead Owner Required",
        meaning: "Lead must have owner before progression.",
        commonCause: "Owner field is missing.",
        fixSteps: ["Assign owner", "Save and retry"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "organizations-accounts",
    title: "Organizations Module: Account Master Data",
    summary: "Detailed account structure and relationship maintenance.",
    type: "documentation",
    module: "clients",
    relatedHref: "/clients",
    tags: ["organizations", "accounts", "crm"],
    difficulty: "beginner",
    audience: ["Sales", "Support"],
    articleSections: [
      {
        heading: "Master Record Standards",
        paragraphs: ["Use one canonical organization per legal entity.", "Attach key contacts and keep status current."],
      },
      {
        heading: "Cross-Module Context",
        paragraphs: ["Link organizations to leads, tickets, and projects.", "Broken links reduce support and sales efficiency."],
      },
    ],
    whenToUse: ["Account setup", "Duplicate cleanup", "Context linkage"],
    steps: ["Search before create", "Create organization", "Attach contacts", "Link related records", "Review duplicates monthly"],
    tips: ["Standardize naming", "Use clear branch suffixes"],
    errorDetails: [
      {
        errorNumber: 9001,
        code: "CLIENT_DUPLICATE_DETECTED",
        httpStatus: 409,
        title: "Duplicate Organization",
        meaning: "Matching organization already exists.",
        commonCause: "No pre-create search.",
        fixSteps: ["Merge records", "Update existing organization instead"],
      },
      {
        errorNumber: 9002,
        code: "CLIENT_LINK_CONSTRAINT_FAILED",
        httpStatus: 400,
        title: "Organization Link Failed",
        meaning: "Related record could not be linked.",
        commonCause: "Invalid related ID or insufficient access.",
        fixSteps: ["Validate related record", "Check permissions", "Retry link action"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "contacts-directory",
    title: "Contacts Module: Person Records and Communication Context",
    summary: "Detailed contact management including dedupe and role labeling.",
    type: "guide",
    module: "contacts",
    relatedHref: "/contacts",
    tags: ["contacts", "crm", "dedupe"],
    difficulty: "beginner",
    audience: ["Sales", "Support"],
    articleSections: [
      {
        heading: "Contact Integrity",
        paragraphs: ["One person should map to one active contact record.", "Normalize phone and email format for cleaner search."],
      },
      {
        heading: "Relationship Clarity",
        paragraphs: ["Mark contact role and owner.", "Keep organization links current for handover quality."],
      },
    ],
    whenToUse: ["Contact creation", "CRM cleanup", "Campaign prep"],
    steps: ["Search by email/phone", "Create or update contact", "Set role and owner", "Link organization", "Merge duplicates"],
    tips: ["Track last verified date", "Prefer update over duplicate create"],
    errorDetails: [
      {
        errorNumber: 15001,
        code: "CONTACT_DUPLICATE_EMAIL",
        httpStatus: 409,
        title: "Duplicate Contact Email",
        meaning: "A contact with this email already exists.",
        commonCause: "Duplicate search was skipped.",
        fixSteps: ["Open existing contact", "Merge instead of creating new record"],
      },
      {
        errorNumber: 15002,
        code: "CONTACT_ORGANIZATION_REQUIRED",
        httpStatus: 400,
        title: "Organization Required",
        meaning: "Operation requires linked organization.",
        commonCause: "Organization link is missing.",
        fixSteps: ["Select/create organization", "Retry save"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "team-module",
    title: "Team Module: Internal Directory and Responsibility Map",
    summary: "Detailed internal user directory operations for collaboration speed.",
    type: "documentation",
    module: "team",
    relatedHref: "/team",
    tags: ["team", "directory", "responsibility"],
    difficulty: "beginner",
    audience: ["All users", "Managers"],
    articleSections: [
      {
        heading: "Directory Purpose",
        paragraphs: ["Team module helps users find the right owner quickly.", "Current role and department data reduce routing delays."],
      },
      {
        heading: "Maintenance Rules",
        paragraphs: ["Keep title, department, and status updated.", "Mark inactive users to prevent wrong assignments."],
      },
    ],
    whenToUse: ["People lookup", "Assignment troubleshooting", "Org update"],
    steps: ["Check your profile entry", "Review key members", "Fix stale profile fields", "Retest assignee pickers"],
    tips: ["Use consistent department names", "Review after org changes"],
    errorDetails: [
      {
        errorNumber: 16001,
        code: "TEAM_MEMBER_NOT_FOUND",
        httpStatus: 404,
        title: "Team Member Not Found",
        meaning: "Requested user entry is unavailable.",
        commonCause: "User deactivated or stale reference.",
        fixSteps: ["Refresh list", "Search by email/login", "Verify in Administration"],
      },
      {
        errorNumber: 16002,
        code: "TEAM_DIRECTORY_PERMISSION_DENIED",
        httpStatus: 403,
        title: "Directory Permission Denied",
        meaning: "User cannot perform this team action.",
        commonCause: "Missing team module permission.",
        fixSteps: ["Grant team.read/write as needed", "Retest operation"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "calendar-module",
    title: "Calendar Module: Scheduling and Time Integrity",
    summary: "Detailed event scheduling with timezone and ownership discipline.",
    type: "guide",
    module: "calendar",
    relatedHref: "/calendar",
    tags: ["calendar", "timezone", "events"],
    difficulty: "intermediate",
    audience: ["All users"],
    articleSections: [
      {
        heading: "Timezone Safety",
        paragraphs: ["System and user timezone must be valid and aligned.", "Invalid timezone values create shifted events and missed reminders."],
      },
      {
        heading: "Event Hygiene",
        paragraphs: ["Each event should have owner and purpose.", "Link events to tasks/projects when events drive execution."],
      },
    ],
    whenToUse: ["Scheduling coordination", "Timezone issue resolution", "Reminder tuning"],
    steps: ["Set timezone", "Create event", "Set reminders", "Invite participants", "Update or cancel promptly"],
    tips: ["Avoid duplicate events", "Use clear titles and agenda notes"],
    errorDetails: [
      {
        errorNumber: 17001,
        code: "CALENDAR_EVENT_CONFLICT",
        httpStatus: 409,
        title: "Event Conflict",
        meaning: "Operation conflicts with existing event constraints.",
        commonCause: "Overlap or stale event version.",
        fixSteps: ["Refresh calendar", "Adjust timing", "Retry update"],
      },
      {
        errorNumber: 17002,
        code: "CALENDAR_TIMEZONE_INVALID",
        httpStatus: 400,
        title: "Invalid Timezone",
        meaning: "Timezone key is invalid or unsupported.",
        commonCause: "Malformed timezone setting.",
        fixSteps: ["Select valid timezone", "Save settings", "Retry event action"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "chat-module",
    title: "Chat Module: Dialog Quality, Links, and Attachments",
    summary: "Detailed chat behavior for dedupe, self-blocking, and message reliability.",
    type: "guide",
    module: "chat",
    relatedHref: "/chat",
    tags: ["chat", "dialogs", "links", "attachments"],
    difficulty: "intermediate",
    audience: ["All users"],
    articleSections: [
      {
        heading: "Dialog Dedupe Rules",
        paragraphs: ["Do not create duplicate dialogs for same participant set.", "New chat picker should exclude self and existing direct dialogs."],
      },
      {
        heading: "Message Rendering",
        paragraphs: ["Links should be clickable and previewable where supported.", "Attachment send should fail fast with explicit retry guidance."],
      },
    ],
    whenToUse: ["Internal collaboration", "Duplicate dialog issues", "Attachment troubleshooting"],
    steps: ["Search existing dialog", "Select valid recipients", "Send contextual message", "Verify link behavior", "Confirm attachment upload"],
    tips: ["One canonical dialog per user pair", "Use group dialogs for team context"],
    errorDetails: [
      {
        errorNumber: 5001,
        code: "CHAT_DIALOG_DUPLICATE",
        httpStatus: 409,
        title: "Duplicate Dialog",
        meaning: "Dialog already exists for that member set.",
        commonCause: "Missing dedupe check before create.",
        fixSteps: ["Open existing dialog", "Normalize member IDs in create payload"],
      },
      {
        errorNumber: 5002,
        code: "CHAT_SELF_MESSAGE_BLOCKED",
        httpStatus: 400,
        title: "Self Message Blocked",
        meaning: "User attempted to chat with own ID.",
        commonCause: "Recipient picker includes current user.",
        fixSteps: ["Remove self from picker", "Use task/note for personal reminders"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "livechat-module",
    title: "Live Chat Module: Queue, Assignment, and Realtime Consistency",
    summary: "Detailed live support operations for message order, assignment, and notifications.",
    type: "tutorial",
    module: "livechat",
    relatedHref: "/livechat",
    tags: ["livechat", "queue", "notifications", "attachments"],
    difficulty: "advanced",
    audience: ["Support agents", "Managers"],
    articleSections: [
      {
        heading: "Conversation Timeline Rules",
        paragraphs: ["Newest message belongs at the bottom.", "Queue sorting should follow clear policy and refresh predictably."],
      },
      {
        heading: "Realtime Reliability",
        paragraphs: ["Notifications should align with unread state.", "Auto-refresh fallback is needed when realtime channel is unstable."],
      },
    ],
    whenToUse: ["Agent operations", "Realtime issue debugging", "Queue optimization"],
    steps: ["Open queue", "Assign unassigned sessions", "Reply with guidance", "Send attachments safely", "Close after confirmation"],
    tips: ["Keep handover notes clear", "Track first response and closure separately"],
    errorDetails: [
      {
        errorNumber: 6001,
        code: "LIVECHAT_ATTACHMENT_FAILED",
        httpStatus: 500,
        title: "Live Chat Attachment Failed",
        meaning: "Attachment send did not complete.",
        commonCause: "Upload endpoint or network failure.",
        fixSteps: ["Retry on stable network", "Check upload logs and MIME limits"],
      },
      {
        errorNumber: 6002,
        code: "LIVECHAT_ASSIGNMENT_CONFLICT",
        httpStatus: 409,
        title: "Assignment Conflict",
        meaning: "Another agent changed assignment first.",
        commonCause: "Concurrent assignment update.",
        fixSteps: ["Refresh queue", "Reopen dialog", "Reassign if needed"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "servicedesk-module",
    title: "Ticket Desk Module: Lifecycle and SLA Discipline",
    summary: "Detailed ticket workflow from intake to resolution quality.",
    type: "guide",
    module: "servicedesk",
    relatedHref: "/servicedesk",
    tags: ["tickets", "sla", "servicedesk"],
    difficulty: "intermediate",
    audience: ["Support teams", "Managers"],
    articleSections: [
      {
        heading: "Lifecycle Control",
        paragraphs: ["Use clear statuses with transition rules.", "Closure should include customer-facing summary and evidence."],
      },
      {
        heading: "SLA Health",
        paragraphs: ["Track first response and update cadence.", "Escalate blockers early with owner information."],
      },
    ],
    whenToUse: ["Support operations", "SLA tuning", "Reopen reduction"],
    steps: ["Create ticket", "Assign owner", "Progress statuses", "Communicate updates", "Close with summary"],
    tips: ["Use templates for recurring issues", "Review reopen causes weekly"],
    errorDetails: [
      {
        errorNumber: 7001,
        code: "SERVICEDESK_STATUS_INVALID",
        httpStatus: 400,
        title: "Invalid Ticket Status",
        meaning: "Ticket status key is not valid.",
        commonCause: "Stale client mapping or unsupported status.",
        fixSteps: ["Use configured status key", "Update status mapping in client"],
      },
      {
        errorNumber: 7002,
        code: "SERVICEDESK_PERMISSION_DENIED",
        httpStatus: 403,
        title: "Ticket Permission Denied",
        meaning: "User cannot perform ticket action.",
        commonCause: "Missing servicedesk write/manage access.",
        fixSteps: ["Grant required role permission", "Retest action"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "products-module",
    title: "Products Module: Catalog Standards and Lifecycle",
    summary: "Detailed product data governance for operational consistency.",
    type: "documentation",
    module: "products",
    relatedHref: "/products",
    tags: ["products", "catalog", "sku"],
    difficulty: "intermediate",
    audience: ["Sales ops", "Finance"],
    articleSections: [
      {
        heading: "Catalog Standards",
        paragraphs: ["Use unique product code and clear naming.", "Set active/inactive lifecycle explicitly."],
      },
      {
        heading: "Dependency Awareness",
        paragraphs: ["Products are referenced in other modules.", "Prefer inactive/archive over hard delete where history exists."],
      },
    ],
    whenToUse: ["Catalog setup", "Pricing rollouts", "Data cleanup"],
    steps: ["Create unique product", "Set status", "Validate dependent flows", "Archive obsolete products"],
    tips: ["Do not reuse old SKU", "Control category taxonomy"],
    errorDetails: [
      {
        errorNumber: 18001,
        code: "PRODUCT_DUPLICATE_CODE",
        httpStatus: 409,
        title: "Duplicate Product Code",
        meaning: "Product code already exists.",
        commonCause: "No uniqueness check before create.",
        fixSteps: ["Search by code", "Use new SKU or update existing record"],
      },
      {
        errorNumber: 18002,
        code: "PRODUCT_REFERENCE_CONSTRAINT",
        httpStatus: 400,
        title: "Reference Constraint",
        meaning: "Product has linked records and cannot be removed directly.",
        commonCause: "Dependent transactions or documents exist.",
        fixSteps: ["Set product inactive", "Reassign references if deletion is required"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "accounting-module",
    title: "Accounting Module: Posting Controls and Reconciliation",
    summary: "Detailed controls for ledger integrity and period operations.",
    type: "guide",
    module: "accounting",
    relatedHref: "/accounting",
    tags: ["accounting", "ledger", "reconciliation"],
    difficulty: "advanced",
    audience: ["Finance", "Auditors"],
    articleSections: [
      {
        heading: "Posting Integrity",
        paragraphs: ["Every entry needs complete source and account mapping.", "Use approval flow before locking periods."],
      },
      {
        heading: "Period Safety",
        paragraphs: ["Locked periods prevent accidental historical edits.", "Use correction entries with audit trail."],
      },
    ],
    whenToUse: ["Month-end close", "Audit prep", "Finance governance"],
    steps: ["Post entries", "Review drafts", "Reconcile balances", "Lock period", "Generate reports"],
    tips: ["Limit manage access", "Never bypass locks with direct DB edits"],
    errorDetails: [
      {
        errorNumber: 19001,
        code: "ACCOUNTING_PERIOD_LOCKED",
        httpStatus: 423,
        title: "Period Locked",
        meaning: "Edit attempted in locked period.",
        commonCause: "Write action after close.",
        fixSteps: ["Post correction in open period", "Request controlled unlock if policy allows"],
      },
      {
        errorNumber: 19002,
        code: "ACCOUNTING_BALANCE_MISMATCH",
        httpStatus: 409,
        title: "Balance Mismatch",
        meaning: "Posting creates inconsistent balances.",
        commonCause: "Invalid mapping or partial posting.",
        fixSteps: ["Review journal lines", "Validate mapping", "Reconcile and repost"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "ebank-module",
    title: "e-Bank Module: Payment Flow and Settlement Checks",
    summary: "Detailed bank transaction handling with approval and matching discipline.",
    type: "tutorial",
    module: "ebank",
    relatedHref: "/ebank",
    tags: ["ebank", "payments", "settlement"],
    difficulty: "advanced",
    audience: ["Finance", "Treasury"],
    articleSections: [
      {
        heading: "Payment Control",
        paragraphs: ["Use maker-checker model for sensitive payments.", "Every payment should reference source documents."],
      },
      {
        heading: "Settlement and Matching",
        paragraphs: ["Match bank lines to accounting records quickly.", "Unmatched lines need owner and resolution date."],
      },
    ],
    whenToUse: ["Payment execution", "Bank reconciliation", "Treasury controls"],
    steps: ["Create request", "Approve payment", "Confirm settlement", "Match ledger entry", "Resolve unmatched lines"],
    tips: ["Use dual approval for high value", "Validate beneficiary master data"],
    errorDetails: [
      {
        errorNumber: 20001,
        code: "EBANK_TRANSFER_REJECTED",
        httpStatus: 422,
        title: "Transfer Rejected",
        meaning: "Bank rejected transfer instruction.",
        commonCause: "Invalid beneficiary or policy check failure.",
        fixSteps: ["Check rejection reason", "Correct details", "Resubmit transfer"],
      },
      {
        errorNumber: 20002,
        code: "EBANK_RECONCILIATION_GAP",
        httpStatus: 409,
        title: "Reconciliation Gap",
        meaning: "Bank line cannot be matched to ledger.",
        commonCause: "Missing reference or delayed posting.",
        fixSteps: ["Search by amount/date/ref", "Create pending match item", "Complete after posting update"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "telephony-module",
    title: "Telephony Module: User Mapping and Call Records",
    summary: "Detailed telephony integration guide for extension mapping and call visibility.",
    type: "guide",
    module: "telephony",
    relatedHref: "/telephony",
    tags: ["telephony", "calls", "extensions", "did"],
    difficulty: "advanced",
    audience: ["Admins", "IT"],
    articleSections: [
      {
        heading: "Mapping Model",
        paragraphs: ["Map each user to extension and DID where required.", "Admins should see all records while users see own records."],
      },
      {
        heading: "Integration Fallbacks",
        paragraphs: ["If provider API is limited, use supported CDR export import.", "Normalize call timestamps and direction for reporting."],
      },
    ],
    whenToUse: ["Telephony setup", "Missing call log troubleshooting", "Admin visibility checks"],
    steps: ["Configure provider", "Map users", "Test call logs", "Verify role visibility", "Audit mappings regularly"],
    tips: ["Sync extension ownership with HR events", "Store provider error payloads"],
    errorDetails: [
      {
        errorNumber: 21001,
        code: "TELEPHONY_USER_MAPPING_MISSING",
        httpStatus: 400,
        title: "User Mapping Missing",
        meaning: "Call record cannot map to app user.",
        commonCause: "Unknown extension or missing DID mapping.",
        fixSteps: ["Create mapping", "Reprocess unmatched records"],
      },
      {
        errorNumber: 21002,
        code: "TELEPHONY_PROVIDER_SYNC_FAILED",
        httpStatus: 502,
        title: "Provider Sync Failed",
        meaning: "Provider sync request failed.",
        commonCause: "Endpoint/auth/network issue.",
        fixSteps: ["Validate credentials", "Retry with backoff", "Use fallback import channel"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "search-module",
    title: "Search Module: Cross-Module Discovery and Error Lookup",
    summary: "Detailed search strategies for records, tags, and help error codes.",
    type: "tutorial",
    module: "search",
    relatedHref: "/search",
    tags: ["search", "filters", "errors"],
    difficulty: "beginner",
    audience: ["All users"],
    articleSections: [
      {
        heading: "Scope and Permissions",
        paragraphs: ["Search returns only modules the user can read.", "Missing results are often permission-related."],
      },
      {
        heading: "Fast Query Patterns",
        paragraphs: ["Use short precise identifiers.", "Search by error code or number for troubleshooting."],
      },
    ],
    whenToUse: ["Record lookup", "Troubleshooting by error code", "Duplicate prevention"],
    steps: ["Start broad search", "Apply module filter", "Search by code/number", "Open and validate result context"],
    tips: ["Fewer terms often works better", "Check permissions when no results appear"],
    errorDetails: [
      {
        errorNumber: 11001,
        code: "SEARCH_REQUEST_FAILED",
        httpStatus: 500,
        title: "Search Request Failed",
        meaning: "Search backend failed temporarily.",
        commonCause: "Endpoint error or malformed request.",
        fixSteps: ["Retry query", "Check server logs", "Validate query payload"],
      },
      {
        errorNumber: 11002,
        code: "SEARCH_FORBIDDEN_MODULE",
        httpStatus: 403,
        title: "Forbidden Module Filter",
        meaning: "User cannot search selected module.",
        commonCause: "Missing module read permission.",
        fixSteps: ["Switch to allowed modules", "Request permission if needed"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
  {
    id: "administration-module",
    title: "Administration Module: RBAC, Settings, and Change Safety",
    summary: "Detailed admin playbook for secure changes and system governance.",
    type: "guide",
    module: "administration",
    relatedHref: "/administration",
    tags: ["administration", "rbac", "security", "settings"],
    difficulty: "advanced",
    audience: ["Admins", "System managers"],
    articleSections: [
      {
        heading: "RBAC Governance",
        paragraphs: ["Define roles by business function and least privilege.", "Use user overrides only for justified exceptions."],
      },
      {
        heading: "Safe Change Process",
        paragraphs: ["Apply high-risk changes in small batches with rollback plan.", "Validate with admin and non-admin accounts after each update."],
        checklist: ["Backup settings", "Apply change", "Verify critical modules", "Record change log"],
        warnings: ["Do not disable protected modules", "Do not grant broad manage rights without review"],
      },
    ],
    whenToUse: ["Permission tuning", "System config changes", "Access incident response"],
    steps: ["Review roles", "Apply minimal changes", "Validate access", "Monitor logs", "Rollback quickly if needed"],
    tips: ["Use staged rollout", "Keep emergency admin account secured"],
    errorDetails: [
      {
        errorNumber: 10001,
        code: "RBAC_OVERRIDE_INVALID",
        httpStatus: 400,
        title: "Invalid RBAC Override",
        meaning: "Override payload is malformed or unsupported.",
        commonCause: "Wrong module/action key format.",
        fixSteps: ["Use UI editor", "Validate keys against module/action definitions"],
      },
      {
        errorNumber: 10002,
        code: "MODULE_TOGGLE_PROTECTED",
        httpStatus: 400,
        title: "Protected Module Toggle Blocked",
        meaning: "Core module cannot be disabled.",
        commonCause: "Attempt to disable home/search/help/administration.",
        fixSteps: ["Leave core module enabled", "Control visibility via permissions"],
      },
    ],
    updatedAt: UPDATED_AT,
  },
];

export function getHelpTopicById(topicId: string) {
  return HELP_TOPICS.find((topic) => topic.id === topicId) ?? null;
}
